name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Code নামাও
        uses: actions/checkout@v3

      - name: Test run করো
        run: bash calculator.sh